ALTER TABLE IF EXISTS knowledge_bases ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS knowledge_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS knowledge_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS faq_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS knowledge_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS rag_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS rag_messages ENABLE ROW LEVEL SECURITY;
