ALTER TABLE IF EXISTS "public"."codm_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."codm_emails" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."carousels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."sequence_counters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
